name: IceStorm

on:
  workflow_dispatch:
  push:
    paths: '.github/workflows/IceStorm.yml'
    branches:
      - main
  schedule:
    - cron: "13 0 * * *"
jobs:
  build-IceStorm:
    name: Build IceStorm
    runs-on: windows-2019

    steps:
      - name: Checkout IceStorm
        uses: actions/checkout@v2
        with:
          repository: YosysHQ/icestorm
          path: icestorm
          
      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            msys/bison
            msys/flex
            msys/libreadline-devel
            msys/gawk
            msys/tcl
            msys/libffi-devel
            msys/pkg-config
            python3
            mingw64/mingw-w64-x86_64-python-pip
            mingw64/mingw-w64-x86_64-python-setuptools
            mingw64/mingw-w64-x86_64-dlfcn
            mingw64/mingw-w64-x86_64-libftdi
            mingw-w64-x86_64-toolchain

      - name: Build IceStorm
        shell: msys2 {0}
        working-directory: icestorm
        run: |
          mkdir buildProducts
          pip3 install xdot
          mingw32-make -j4
          mingw32-make DESTDIR=../../buildProducts PREFIX='' install
          
      # TODO Tests of some kind to validate it built properly
          
      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: icestorm
          path: buildProducts

      - name: Zip Release Files
        run: |
          Compress-Archive -Path .\buildProducts\* -DestinationPath buildProducts.zip

      - name: Update tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/icestorm/nightly",
              sha: context.sha
            })

      - name: Deploy Nightly
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/davidcorrigan714/nextpnr-actions-prototype/releases/35743877/assets{?name,label}
          release_id: 35743877
          asset_path: ./buildProducts.zip
          asset_name: IceStorm-Win-x86_64-$$.zip
          asset_content_type: application/zip
          max_releases: 20
