name: nextpnr-ci

on:
  workflow_dispatch:
  push:
    paths: '.github/workflows/nextpnr.yml'
    
jobs:
  next-pnr:
    name: prjtrellis
    #runs-on: self-hosted
    runs-on: windows-2019
    timeout-minutes: 240

    steps:
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1
  
      # nextpnr fails to build with Python 3.7.9, not entirely sure why,
      # but there's weird errors about 'copysign' in the VS header files.
      # Might be conflicting macro definitions for copysign.
      # Should be able to remove this if GitHub upgrades their images
      - name: Upgrade Python
        run: |
          $WebClient = New-Object System.Net.WebClient
          $WebClient.DownloadFile("https://www.python.org/ftp/python/3.9.1/python-3.9.1-amd64.exe",(Get-Location).tostring()+"\python3.exe")
          cmd /c start /wait python3.exe /quiet TargetDir=$Env:GITHUB_WORKSPACE\python Shortcuts=0 Include_launcher=1 PrependPath=1
          dir $Env:GITHUB_WORKSPACE\python
  

      - name: Checkout prjtrellis
        uses: actions/checkout@v2
        with:
          repository: YosysHQ/prjtrellis
          path: prjtrellis
          submodules: recursive
          fetch-depth: 0

      - name: Build prjtrellis
        working-directory: prjtrellis\libtrellis\
        run: |
          cmake -DPython_ROOT_DIR='$Env:GITHUB_WORKSPACE\python' -DCMAKE_CXX_FLAGS='/D "BOOST_ALL_DYN_LINK"' .
          msbuild /t:Build /p:Configuration=Release libtrellis.sln
          
      - name: Install prjtrellis
        run: |
          mkdir releaseDir
          cmake -DCMAKE_INSTALL_PREFIX="releaseDir" -DBUILD_TYPE=Release -P .\prjtrellis\libtrellis\cmake_install.cmake
          dir releaseDir
          dir $Env:GITHUB_WORKSPACE\prjtrellis\libtrellis\Release
      - name: Checkout nextpnr
        uses: actions/checkout@v2
        with:
          repository: YosysHQ/nextpnr
          path: nextpnr

      - name: Build nextpnr
        working-directory: nextpnr
        timeout-minutes: 240
        run: |
          $env:Path += ";"+$Env:BOOST_ROOT_1_72_0+"\lib"
          vcpkg.exe install qt5-base:x64-windows eigen3:x64-windows
          vcpkg.exe integrate install
          $Env:PYTHONPATH = "$Env:GITHUB_WORKSPACE\prjtrellis\util\common;$Env:GITHUB_WORKSPACE\prjtrellis\timing\util"
          cmake . -DPython_ROOT_DIR='$Env:GITHUB_WORKSPACE\python' -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_FLAGS='/D "BOOST_ALL_DYN_LINK" /D "WIN32" /EHsc' -DARCH=ecp5 -DCMAKE_PREFIX_PATH="$Env:GITHUB_WORKSPACE\prjtrellis\libtrellis\Release"
          msbuild /t:Build /p:Configuration=Release /p:Platform=x64 nextpnr.sln
      
      - name: Install nextpnr
        run: |
          cmake -DCMAKE_INSTALL_PREFIX="releaseDir" -DBUILD_TYPE=Release -P .\nextpnr\cmake_install.cmake 
          dir releasedir
