name: nextpnr-ci

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  next-pnr:
    # Name the Job
    name: Build nextpnr
    # Set the type of machine to run on
    runs-on: windows-2019

    steps:
      - name: Testing
        run: |
          echo $Env:BOOST_ROOT_1_72_0
          $Env:BOOST_ROOT = $Env:BOOST_ROOT_1_72_0
          dir $Env:BOOST_ROOT
          dir "C:\Program Files (x86)\Microsoft Visual Studio\"
      
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout nextpnr
        uses: actions/checkout@v2
        with:
          repository: YosysHQ/nextpnr
          submodules: recursive
        
      - name: Checkout prjtrellis
        uses: actions/checkout@v2
        with:
          repository: YosysHQ/prjtrellis
      
      - name: Checkout yosys
        uses: actions/checkout@v2
        with:
          repository: YosysHQ/yosys
      
      - name: Checkout icestorm
        uses: actions/checkout@v2
        with:
          repository: YosysHQ/icestorm
