name: nightly-test

on:
  workflow_dispatch:
  push:
    paths: '.github/workflows/nightly-test.yml'
    branches:
      - main
  schedule:
    - cron: "7 0 * * *"
jobs:
  build-nightly-test:
    name: Nightly Test
    runs-on: windows-2019

    steps:
      - name: Build Something
        working-directory: .
        run: |
          mkdir output
          echo "Heyo" > output/test.txt

      - name: GitHub Script
        uses: actions/github-script@v3.1.0
        with:
          # The script to run
          script: |
            const releases = await github.releases.release_for_tag( "davidcorrigan714/nextpnr-actions-prototype", "prjtrellis/nightly" )
            console.log(releases)
            //const diff_url = context.payload.pull_request.diff_url
            //const result = await github.request(diff_url)
            //console.log(result)


      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          retention-days: 30
          if-no-files-found: error
          name: output
          path: ./output/

      - name: Zip Release Files
        run: |
          Compress-Archive -Path .\output\* -DestinationPath buildProducts.zip

      - name: Update tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/test/nightly",
              sha: context.sha
            })

      - name: Deploy Nightly
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/davidcorrigan714/nextpnr-actions-prototype/releases/35827933/assets{?name,label}
          release_id: 35827933
          asset_path: ./buildProducts.zip
          asset_name: test-Win-x86_64-$$.zip
          asset_content_type: application/zip
          max_releases: 20

    
