name: nightly-test

on:
  workflow_dispatch:
  push:
    paths: '.github/workflows/nightly-test.yml'
    branches:
      - main
  schedule:
    - cron: "13 0 * * *"
jobs:
  build-nightly-test:
    name: Nightly Test
    runs-on: windows-2019

    steps:
      - name: Build Something
        working-directory: .
        run: |
          mkdir output
          echo "Heyo" > output/test.txt

      - name: GitHub Script
        uses: actions/github-script@v3.1.0
        with:
          # The script to run
          script: |
            const releases = await github.repos.getReleaseByTag({
             owner: "davidcorrigan714",
             repo: "nextpnr-actions-prototype",
             tag: "prjtrellis/nightly" });
            var releaseId = releases.data.id;

            const releaseAssets = await github.repos.listReleaseAssets({
             owner: "davidcorrigan714",
             repo: "nextpnr-actions-prototype",
             release_id: releaseId});
            var releaseAssetsData = releaseAssets.data;
            
            var latestAssetDate = "0000-00-00";
            var latestAssetUrl = "";
            for(var asset in releaseAssetsData){
              if(releaseAssetsData[asset].created_at > latestAssetDate){
                console.log("New latest");
                latestAssetDate = releaseAssetsData[asset].created_at;
                latestAssetUrl = releaseAssetsData[asset].browser_download_url;
              }
            }

            console.log("Downloading: " + latestAssetUrl);

            var https = require('https');
            var fs = require('fs');

            var dest = 'prjtrellis.zip';
            var url = latestAssetUrl;

            var file = fs.createWriteStream(dest);
            https.get(url, function(response) {
              response.pipe(file);
              file.on('finish', function() {
                file.close();
              });
            });



      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          retention-days: 30
          if-no-files-found: error
          name: output
          path: ./output/

      - name: Zip Release Files
        run: |
          Compress-Archive -Path .\output\* -DestinationPath buildProducts.zip

      - name: Update tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/test/nightly",
              sha: context.sha
            })

      - name: Deploy Nightly
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/davidcorrigan714/nextpnr-actions-prototype/releases/35827933/assets{?name,label}
          release_id: 35827933
          asset_path: ./buildProducts.zip
          asset_name: test-Win-x86_64-$$.zip
          asset_content_type: application/zip
          max_releases: 20

    
