name: prjoxide

on:
  workflow_dispatch:
  push:
    paths: '.github/workflows/prjoxide.yml'
    branches:
      - main
  schedule:
    - cron: "13 0 * * *"
jobs:
  build-prjoxide:
    name: Project Oxide
    runs-on: windows-2019

    steps:
      - name: Checkout Oxide
        uses: actions/checkout@v2
        with:
          submodules: true
          repository: daveshah1/prjoxide
          path: prjoxide
          
      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-rust
            base-devel

      - name: Build prjoxide
        shell: msys2 {0}
        working-directory: prjoxide/libprjoxide
        run: |
          mkdir output
          cargo install --path prjoxide --root ./output
          
      # TODO Tests of some kind to validate it built properly
          
      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: prjoxide
          path: prjoxide/libprjoxide/output/

      - name: Zip Release Files
        run: |
          Compress-Archive -Path .\prjoxide\libprjoxide\output\* -DestinationPath buildProducts.zip

      - name: Update tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/prjoxide/nightly",
              sha: context.sha
            })

      - name: Deploy Nightly
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/davidcorrigan714/nextpnr-actions-prototype/releases/35808209/assets{?name,label}
          release_id: 35808209
          asset_path: ./buildProducts.zip
          asset_name: prjoxide-Win-x86_64-$$.zip
          asset_content_type: application/zip
          max_releases: 20
