name: Yosys

on:
  push:
    paths: '.github/workflows/yosys.yml'

jobs:
  next-pnr:
    name: Build Yosys
    runs-on: windows-2019

    steps:
      - name: Checkout yosys
        uses: actions/checkout@v2
        with:
          repository: YosysHQ/yosys
          path: yosys
          
      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            msys/bison
            msys/flex
            msys/libreadline-devel
            msys/gawk
            msys/tcl
            msys/libffi-devel
            msys/pkg-config
            git
            python3
            mingw64/mingw-w64-x86_64-python3-pip
            mingw64/mingw-w64-x86_64-dlfcn
            mingw-w64-x86_64-toolchain

      - name: Build Yosys
        shell: msys2 {0}
        working-directory: yosys
        run: |
          mkdir buildProducts
          pip3 install xdot
          mingw32-make config-msys2-64
          mingw32-make -j4
          mingw32-make DESTDIR=buildProducts PREFIX='' install
          
      - name: Build Yosys
        shell: msys2 {0}
        working-directory: yosys
        run: |
          dir buildProducts
