name: yosys

on:
  push:
    paths: 'yosys.yml'

jobs:
  next-pnr:
    name: Build yosys
    runs-on: windows-2019

    steps:
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Testing
        run: |
          dir "C:\msys64"

      - name: Checkout yosys
        uses: actions/checkout@v2
        with:
          repository: YosysHQ/yosys
          path: yosys
          
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            msys/bison
            msys/flex
            msys/libreadline-devel
            msys/gawk
            msys/tcl
            msys/libffi-devel
            msys/pkg-config
            python
            python3
            mingw64/mingw-w64-x86_64-libftdi
            mingw64/mingw-w64-x86_64-python3-pip
            mingw64/mingw-w64-x86_64-python2-pip
            mingw64/mingw-w64-x86_64-dlfcn
            mingw-w64-x86_64-toolchain

          
      - name: MSYS2 Testing
        run: |
          echo "Heyo"
          
        
